# Tanuki Theme - Blog Example
base_url = "https://ajd323.github.io/Fast-Robots-MAE4190/"
title = "Andrew D'Onofrio Fast Robots Portfolio"
description = "A compilation of labs from MAE 4190: Fast Robots class created by Andrew D'Onofrio"
theme = "tanuki"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
render_emoji = true
smart_punctuation = true

[extra]
mode = "docs"
show_theme_toggle = true
show_about_section = true

# Author info
[extra.author]
name = "Andrew D'Onofrio"
bio = "Senior Mechanical Engineering Student (B.S. '26)"

# Hero section
[extra.hero]
title = "Fast Robots by Andrew D'Onofrio"
subtitle = "MAE4190 Student Portfolio Page"
[extra.hero.cta]
text = "Read the page!"
url = "/docs/"

# About preview on homepage
[extra.about]
summary = "Documentation and insights from MAE 4190 - Fast Robots course."

# Social links
[extra.social]
github = "https://github.com/ajd323"

# Navigation
[[extra.nav]]
name = "Blog"
url = "/blog/"
