# Tanuki Theme - Example
base_url = "https://ajd323.github.io/Fast-Robots-MAE4190"
title = "Andrew DOnofrio Fast Robots (MAE4190) Portfolio"
description = """
Hello, my name is Andrew DOnofrio â€” welcome to my portfolio for MAE 4190: Fast Robots!
Please read through for projects relating to in-depth documentation on mechatronics and complex systems, and see my about page to learn more about me!
"""

theme = "tanuki"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
render_emoji = true
smart_punctuation = true

[extra]
mode = "docs"
show_theme_toggle = true
# show_about_section = false

# Author info
[extra.author]
name = "Andrew DOnofrio"
bio = "Senior Mechanical Engineering Student (B.S. '26)"

# Hero section
# [extra.hero]
# title = "Fast Robots by Andrew DOnofrio"
# subtitle = "MAE4190 Student Portfolio Page"

# Social links
[extra.social]
github = "https://github.com/ajd323"

# Navigation
[[extra.nav]]
name = "Home"
url = "https://ajd323.github.io/Fast-Robots-MAE4190/"

[[extra.nav]]
name = "Labs"
url = "https://ajd323.github.io/Fast-Robots-MAE4190/blog/"

[[extra.nav]]
name = "About"
url = "https://ajd323.github.io/Fast-Robots-MAE4190/articles/"